
package gt.edu.umg.proyecto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ActualizarP extends javax.swing.JFrame {
    private Connection conexion;
    DefaultTableModel model;
    
    public ActualizarP() {
        initComponents();
        cargar("");
        this.conectar();
        this.setLocationRelativeTo(null);
    }
    public void conectar(){
        ConectarL bd = new ConectarL();
        //Conexion es un objeto
        conexion = bd.getConexion();
    }
    void deshabilitar(){
    tfCodigo.setEnabled(true);
    tfDescripcion.setEnabled(true);
    tfPrecio.setEnabled(true);
    btnnuevo.setEnabled(true);
    btnactualizar.setEnabled(true);
    }
    void clean(){
    tfCodigo.setText("");
    tfDescripcion.setText("");
    tfPrecio.setText("");
    tfActualizar.setText("");
    }
    void cargar(String valor){
    String mostrar="SELECT Id, Producto, Cantidad, Precio FROM producto;";
    String []titulos={"Id","Producto","Cantidad","Precio"};
    String []Registros=new String[4];
    model= new DefaultTableModel(null,titulos);
        try {
            
              Statement st = conexion.createStatement();
              ResultSet rs = st.executeQuery(mostrar);
              while(rs.next())
              {
                  Registros[0]= rs.getString("Id");
                  Registros[1]= rs.getString("Producto");
                  Registros[2]= rs.getString("Cantidad");
                  Registros[3]= rs.getString("Precio");
                  model.addRow(Registros);
              }
              tbcliente.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(ActualizarP.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        tfPrecio = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        tfActualizar = new javax.swing.JTextField();
        tfMostrar = new javax.swing.JButton();
        btnguardar2 = new javax.swing.JButton();
        btnguardar1 = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar productos");
        setBackground(new java.awt.Color(255, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setText("Actualizar Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 390, -1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Cantidad (libras)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, -1));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Q.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 20, 20));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Id Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, -1));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Precio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 80, 20));
        getContentPane().add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 70, -1));
        getContentPane().add(tfDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 130, -1));
        getContentPane().add(tfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 60, -1));

        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/btnactualizar.png"))); // NOI18N
        btnactualizar.setBorder(null);
        btnactualizar.setBorderPainted(false);
        btnactualizar.setContentAreaFilled(false);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        tfActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(tfActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 60, -1));

        tfMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/btnmostrartabla.png"))); // NOI18N
        tfMostrar.setBorder(null);
        tfMostrar.setBorderPainted(false);
        tfMostrar.setContentAreaFilled(false);
        tfMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(tfMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 110, 30));

        btnguardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Confirmar.jpeg"))); // NOI18N
        btnguardar2.setBorder(null);
        btnguardar2.setBorderPainted(false);
        btnguardar2.setContentAreaFilled(false);
        btnguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        btnguardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Cancelar.jpeg"))); // NOI18N
        btnguardar1.setBorder(null);
        btnguardar1.setBorderPainted(false);
        btnguardar1.setContentAreaFilled(false);
        btnguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Java_btnnuevo.png"))); // NOI18N
        btnnuevo.setBorder(null);
        btnnuevo.setBorderPainted(false);
        btnnuevo.setContentAreaFilled(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Idproducto", "Producto", "Cantidad", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tbcliente);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 600, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
    try {
        conexion.setAutoCommit(false);
        LoggerUtil.logInfo("Start transaction");
       PreparedStatement pst = conexion.prepareStatement("UPDATE producto SET producto=?, cantidad=?, precio=? WHERE Id=?");
pst.setString(1, tfCodigo.getText());
pst.setString(2, tfDescripcion.getText());
pst.setString(3, tfPrecio.getText());
pst.setString(4, tfActualizar.getText());
int resultado = pst.executeUpdate();
        cargar("");
        if (resultado==1){
                JOptionPane.showMessageDialog(null,"Producto actualizado");
                        LoggerUtil.logInfo(MessageFormat.format("Confirmado {0} y {1}",tfCodigo,tfPrecio));

            }
            else {
                JOptionPane.showMessageDialog(null,"El producto no existe");
                LoggerUtil.logInfo("Producto no existe"); 
            }
        }catch(Exception e){
            System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(null,"Ocurrio un error");
                            LoggerUtil.logInfo(MessageFormat.format( "Error {0}", e));
        }
    
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
    deshabilitar();
    clean();
    tfCodigo.requestFocus();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void tfMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMostrarActionPerformed
        cargar("");
    }//GEN-LAST:event_tfMostrarActionPerformed

    private void tfActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActualizarActionPerformed

    private void btnguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar2ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea guardar los cambios?");
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                conexion.commit();
                JOptionPane.showMessageDialog(null,"Cambios guardados");
                LoggerUtil.logInfo(MessageFormat.format("Commit: {0}", opcion));
            } catch (SQLException ex) {
                Logger.getLogger(ActualizarP.class.getName()).log(Level.SEVERE, null, ex);
                                LoggerUtil.logInfo(MessageFormat.format( "Error {0}", ex));
            }
        }
    }//GEN-LAST:event_btnguardar2ActionPerformed

    private void btnguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar1ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea revertir los cambios?");
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                conexion.rollback();
                JOptionPane.showMessageDialog(null,"Cambios revertidos");
                LoggerUtil.logInfo(MessageFormat.format("Rollback: {0}", opcion));
            } catch (SQLException ex) {
                Logger.getLogger(ActualizarP.class.getName()).log(Level.SEVERE, null, ex);
                                LoggerUtil.logInfo(MessageFormat.format( "Error {0}", ex));
            }
        }
    }//GEN-LAST:event_btnguardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnguardar1;
    private javax.swing.JButton btnguardar2;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbcliente;
    private javax.swing.JTextField tfActualizar;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JButton tfMostrar;
    private javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
