
package gt.edu.umg.proyecto;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class AñadirPro extends javax.swing.JFrame {
   private Connection conexion;

    public AñadirPro() {
        initComponents();
        this.conectar();
        this.setLocationRelativeTo(null);
    }
    public void conectar(){
        ConectarL bd = new ConectarL();
        //Conexion es un objeto
        conexion = bd.getConexion();
    }
    void deshabilitar(){
    tfNombres.setEnabled(true);
    tfApellidos.setEnabled(true);
    tfDireccion.setEnabled(true);
    tfNumero.setEnabled(true);
    /*tfMarca.setEnabled(true);*/
    btnnuevo.setEnabled(true);
    btnguardar.setEnabled(true);
    }
    void clean(){
    tfNombres.setText("");
    tfApellidos.setText("");
    tfDireccion.setText("");
    tfNumero.setText("");
    /*tfMarca.setText("");*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfApellidos = new javax.swing.JTextField();
        tfNombres = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnguardar2 = new javax.swing.JButton();
        btnguardar1 = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir proveedores");
        setMinimumSize(new java.awt.Dimension(600, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setText("Agregar nuevo proveedor");
        jLabel1.setAlignmentX(10.0F);
        jLabel1.setAlignmentY(8.5F);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 40));

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Apellidos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, 30));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Nombres:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, 30));

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Telefono:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 110, 30));

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Direccion:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 110, 30));

        tfApellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tfApellidos.setFocusCycleRoot(true);
        getContentPane().add(tfApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 140, -1));
        getContentPane().add(tfNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 120, -1));
        getContentPane().add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 120, 30));
        getContentPane().add(tfNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 120, 30));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Java_botonguardar.png"))); // NOI18N
        btnguardar.setBorder(null);
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.setPreferredSize(new java.awt.Dimension(63, 26));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 70, 30));

        btnguardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Confirmar.jpeg"))); // NOI18N
        btnguardar2.setBorder(null);
        btnguardar2.setBorderPainted(false);
        btnguardar2.setContentAreaFilled(false);
        btnguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        btnguardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Cancelar.jpeg"))); // NOI18N
        btnguardar1.setBorder(null);
        btnguardar1.setBorderPainted(false);
        btnguardar1.setContentAreaFilled(false);
        btnguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Java_btnnuevo.png"))); // NOI18N
        btnnuevo.setBorder(null);
        btnnuevo.setBorderPainted(false);
        btnnuevo.setContentAreaFilled(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgregarC.png"))); // NOI18N
        jLabel25.setPreferredSize(new java.awt.Dimension(63, 26));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
    String Nombre = tfNombres.getText();
    String Apellido = tfApellidos.getText();
    String Direccion = tfDireccion.getText();
    String Numero = tfNumero.getText();
    /*String Marca = tfMarca.getText();*/
    
    String sql = "Insert Into Proveedor values (null, '"+Nombre+"', '"+Apellido+"', '"+Direccion+"', '"+Numero+"',null);";
    try{
        Statement st = conexion.createStatement();
        conexion.setAutoCommit(false);
        LoggerUtil.logInfo("Start transaction");
        int resultado = st.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Proveedor guardado");
                LoggerUtil.logInfo(MessageFormat.format("Confirmado {0} y {1}", Nombre,Apellido));

        /*try{
            Statement st1 = conexion.createStatement();
            int resultado1 = st1.executeUpdate(sql1);
            JOptionPane.showMessageDialog(null,"Cliente guardado");
         }catch(Exception error){
            JOptionPane.showMessageDialog(null,"Ocurrio un error");
         }*/
      
    }catch(Exception error){
         JOptionPane.showMessageDialog(null,"Ocurrio un error");
         LoggerUtil.logInfo(MessageFormat.format( "Error {0}", error));
    }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
    deshabilitar();
    clean();
    tfNombres.requestFocus();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar2ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea guardar los cambios?");
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                conexion.commit();
                JOptionPane.showMessageDialog(null,"Cambios guardados");
                LoggerUtil.logInfo(MessageFormat.format("Commit: {0}", opcion));
            } catch (SQLException ex) {
                Logger.getLogger(AñadirPro.class.getName()).log(Level.SEVERE, null, ex);
                                LoggerUtil.logInfo(MessageFormat.format( "Error {0}", ex));
            }
        }
    }//GEN-LAST:event_btnguardar2ActionPerformed

    private void btnguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar1ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea revertir los cambios?");
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                conexion.rollback();
                JOptionPane.showMessageDialog(null,"Cambios revertidos");
                                LoggerUtil.logInfo(MessageFormat.format("Rollback: {0}", opcion));
            } catch (SQLException ex) {
                Logger.getLogger(AñadirPro.class.getName()).log(Level.SEVERE, null, ex);
                                LoggerUtil.logInfo(MessageFormat.format( "Error {0}", ex));
            }
        }
    }//GEN-LAST:event_btnguardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnguardar1;
    private javax.swing.JButton btnguardar2;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfNumero;
    // End of variables declaration//GEN-END:variables
}
