/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gt.edu.umg.proyecto;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class AñadirP extends javax.swing.JFrame {
    private Connection conexion;
    
    public AñadirP() {
        initComponents();
        this.conectar();
        this.setLocationRelativeTo(null);
    }
    public void conectar(){
        ConectarL bd = new ConectarL();
        //Conexion es un objeto
        conexion = bd.getConexion();
    }
    void deshabilitar(){
    tfProducto.setEnabled(true);
    tfCantidad.setEnabled(true);
    tfPrecio.setEnabled(true);
    btnnuevo.setEnabled(true);
    btnguardar.setEnabled(true);
    }
    void clean(){
    tfProducto.setText("");
    tfCantidad.setText("");
    tfPrecio.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfProducto = new javax.swing.JTextField();
        tfCantidad = new javax.swing.JTextField();
        tfPrecio = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnguardar2 = new javax.swing.JButton();
        btnguardar1 = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir productos");
        setBackground(new java.awt.Color(255, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setText("Agregar Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 310, -1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Cantidad (libras)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 150, -1));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, 20));

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Q.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 20, 20));
        getContentPane().add(tfProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, -1));
        getContentPane().add(tfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 130, -1));

        tfPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(tfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 70, -1));

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Java_botonguardar.png"))); // NOI18N
        btnguardar.setBorder(null);
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        btnguardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Confirmar.jpeg"))); // NOI18N
        btnguardar2.setBorder(null);
        btnguardar2.setBorderPainted(false);
        btnguardar2.setContentAreaFilled(false);
        btnguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        btnguardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Cancelar.jpeg"))); // NOI18N
        btnguardar1.setBorder(null);
        btnguardar1.setBorderPainted(false);
        btnguardar1.setContentAreaFilled(false);
        btnguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Java_btnnuevo.png"))); // NOI18N
        btnnuevo.setBorder(null);
        btnnuevo.setBorderPainted(false);
        btnnuevo.setContentAreaFilled(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo_hojas.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
    String Producto = tfProducto.getText();
    String Cantidad = tfCantidad.getText();
    String Precio = tfPrecio.getText();
     
    String sql = "Insert Into Producto values (null, '"+Producto+"', '"+Cantidad+"', '"+Precio+"',null);";
    try{
        conexion.setAutoCommit(false);
        LoggerUtil.logInfo("Start transaction");
        Statement st = conexion.createStatement();
        int resultado = st.executeUpdate(sql);       
        JOptionPane.showMessageDialog(null,"Producto guardado");
                LoggerUtil.logInfo(MessageFormat.format("Confirmado {0} y {1}", Producto, Cantidad));

     }catch(Exception error){
        JOptionPane.showMessageDialog(null,"Ocurrio un error");
        LoggerUtil.logInfo(MessageFormat.format( "Error {0}", error));
    }
    
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
    deshabilitar();
    clean();
    tfProducto.requestFocus();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void tfPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecioActionPerformed

    private void btnguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar2ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea guardar los cambios?");
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                conexion.commit();
                JOptionPane.showMessageDialog(null,"Cambios guardados");
                LoggerUtil.logInfo(MessageFormat.format("Commit: {0}", opcion));
            } catch (SQLException ex) {
                Logger.getLogger(AñadirP.class.getName()).log(Level.SEVERE, null, ex);
                                LoggerUtil.logInfo(MessageFormat.format( "Error {0}", ex));
            }
        }
    }//GEN-LAST:event_btnguardar2ActionPerformed

    private void btnguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar1ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea revertir los cambios?");
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                conexion.rollback();
                JOptionPane.showMessageDialog(null,"Cambios revertidos");
                                LoggerUtil.logInfo(MessageFormat.format("Rollback: {0}", opcion));
            } catch (SQLException ex) {
                Logger.getLogger(AñadirP.class.getName()).log(Level.SEVERE, null, ex);
                                LoggerUtil.logInfo(MessageFormat.format( "Error {0}", ex));
            }
        }
    }//GEN-LAST:event_btnguardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnguardar1;
    private javax.swing.JButton btnguardar2;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfProducto;
    // End of variables declaration//GEN-END:variables
}
