/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gt.edu.umg.proyecto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BorrarP extends javax.swing.JFrame {
    private Connection conexion;
    DefaultTableModel model;
    
    public BorrarP() {
        initComponents();
        cargar("");
        this.conectar();
        this.setLocationRelativeTo(null);
    }
    public void conectar(){
        ConectarL bd = new ConectarL();
        //Conexion es un objeto
        conexion = bd.getConexion();
    }
    void deshabilitar(){
    tfborrar.setEnabled(true);
    btnnuevo.setEnabled(true);
    btnborrar.setEnabled(true);
    }
    void clean(){
    tfborrar.setText("");
    
    }
    void cargar(String valor){
    String mostrar="SELECT Id, Producto, Cantidad, Precio FROM producto;";
    String []titulos={"Id","Producto","Cantidad","Precio"};
    String []Registros=new String[4];
    model= new DefaultTableModel(null,titulos);
        try {
              Statement st = conexion.createStatement();
              ResultSet rs = st.executeQuery(mostrar);
              while(rs.next())
              {
                  Registros[0]= rs.getString("Id");
                  Registros[1]= rs.getString("Producto");
                  Registros[2]= rs.getString("Cantidad");
                  Registros[3]= rs.getString("Precio");
                  model.addRow(Registros);
              }
              tbcliente.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(ActualizarP.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfborrar = new javax.swing.JTextField();
        btnborrar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnguardar2 = new javax.swing.JButton();
        btnguardar1 = new javax.swing.JButton();
        tfMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borar productos");
        setBackground(new java.awt.Color(255, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Borrar Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 340, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id del producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, -1));
        getContentPane().add(tfborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 70, -1));

        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/btnborrar.jpg"))); // NOI18N
        btnborrar.setBorder(null);
        btnborrar.setBorderPainted(false);
        btnborrar.setContentAreaFilled(false);
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Java_btnnuevo.png"))); // NOI18N
        btnnuevo.setBorder(null);
        btnnuevo.setBorderPainted(false);
        btnnuevo.setContentAreaFilled(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        btnguardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Confirmar.jpeg"))); // NOI18N
        btnguardar2.setBorder(null);
        btnguardar2.setBorderPainted(false);
        btnguardar2.setContentAreaFilled(false);
        btnguardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        btnguardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/Cancelar.jpeg"))); // NOI18N
        btnguardar1.setBorder(null);
        btnguardar1.setBorderPainted(false);
        btnguardar1.setContentAreaFilled(false);
        btnguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        tfMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BOTONES/btnmostrartabla.png"))); // NOI18N
        tfMostrar.setBorder(null);
        tfMostrar.setBorderPainted(false);
        tfMostrar.setContentAreaFilled(false);
        tfMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(tfMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Producto", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbcliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 600, 90));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BorrarC.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
    String idproducto = tfborrar.getText();
        String sql = "Delete From producto where id ="+idproducto+";";
        System.out.println(sql);

        try{
            conexion.setAutoCommit(false);
            LoggerUtil.logInfo("Start transaction");
            Statement st = conexion.createStatement();
            int resultado = st.executeUpdate(sql);
            if (resultado==1){
                JOptionPane.showMessageDialog(null,"Producto borrado");
                LoggerUtil.logInfo(MessageFormat.format("Confirmado borrado {0}", idproducto));

                cargar("");
            }
            else {
                JOptionPane.showMessageDialog(null,"El producto no existe");
                LoggerUtil.logInfo("El producto no existe"); 
                cargar("");
            }
        }catch(Exception error){
            JOptionPane.showMessageDialog(null,"Ocurrio un error");
            LoggerUtil.logInfo(MessageFormat.format( "Error {0}", error));
            cargar("");
        }
    
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
    deshabilitar();
    clean();
    tfborrar.requestFocus();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void tfMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMostrarActionPerformed
        cargar("");
    }//GEN-LAST:event_tfMostrarActionPerformed

    private void btnguardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar2ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea guardar los cambios?");
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                conexion.commit();
                JOptionPane.showMessageDialog(null,"Cambios guardados");
                LoggerUtil.logInfo(MessageFormat.format("Commit: {0}", opcion));
            } catch (SQLException ex) {
                Logger.getLogger(BorrarP.class.getName()).log(Level.SEVERE, null, ex);
                                LoggerUtil.logInfo(MessageFormat.format( "Error {0}", ex));
            }
        }
    }//GEN-LAST:event_btnguardar2ActionPerformed

    private void btnguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardar1ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea revertir los cambios?");
        if (opcion == JOptionPane.YES_OPTION) {
            try {
                conexion.rollback();
                JOptionPane.showMessageDialog(null,"Cambios revertidos");
                                LoggerUtil.logInfo(MessageFormat.format("Rollback: {0}", opcion));
            } catch (SQLException ex) {
                Logger.getLogger(BorrarP.class.getName()).log(Level.SEVERE, null, ex);
                                LoggerUtil.logInfo(MessageFormat.format( "Error {0}", ex));
            }
        }
    }//GEN-LAST:event_btnguardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrarP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btnguardar1;
    private javax.swing.JButton btnguardar2;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbcliente;
    private javax.swing.JButton tfMostrar;
    private javax.swing.JTextField tfborrar;
    // End of variables declaration//GEN-END:variables
}
